# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20180214_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='network',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='network',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
